Allows changes to RDS to be applied immediately
Flaconi/terraform-aws-microservice pull request #46
Opened 2021-01-07 18:44 UTC by danvaida

Upcoming release version: `v2.9.2`

2021-01-07 18:46 UTC, danvaida commented
Failed due to `toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit`

2021-01-08 09:45 UTC, ronny-panknin-flaconi requested changes

2021-01-08 09:45 UTC, ronny-panknin-flaconi commented on examples/rds/main.tf
> +  apply_immediately = true
`rds_apply_immediately = true`

2021-01-08 10:30 UTC, ronny-panknin-flaconi approved these changes
:octocat:

2021-01-11 09:57 UTC, merged